### PR TITLE
Show the DataView when a new report is created #1738

### PR DESCRIPTION
**Pull request by wimjongman**
When a new report is created, the first step is to add a data source and data set.

### CODE REVIEW

**Review by speckyspooky — APPROVED** [review]
Looks good to me.

**Comment by merks** [comment]
@wimjongman  @speckyspooky 

This is looks good to go.  What's holding this up?

**Comment by speckyspooky** [comment]
Decision by Wim, for me it is fine too.

**Comment by merks** [comment]
This is a strange build. 

https://ci.eclipse.org/birt/job/build/job/Show_the_DataView_when_a_new_report_is_created_%25231738/

**Pull request merged**
