### PR TITLE
Enhance the excel emitter with force recalculation option (#1651)

### PR DESCRIPTION
**Pull request by speckyspooky**
enhance the excel emitter with force recalculation option (#1651)

### CODE REVIEW

**Review by merks — APPROVED** [review]
I'm not actually qualified to review this type of thing.  But of looks fine in terms of following the existing design pattern.

**Comment by merks** [comment]
@speckyspooky 

BTW, the master builds are failing quite regularly because of memory restriction violations.  I will try to get this ironed out, but I need the help of the Foundation staff to come up with a reliable solution.  Mostly right now I just kick the build again and hope for the best:

https://ci.eclipse.org/birt/job/build/job/master/

Also, if  the following branch is stale, could you please delete it?

https://github.com/eclipse-birt/birt/tree/issue-1089

**Comment by speckyspooky** [comment]
I deleted the branch of issue-1089

**Comment by hvbtup** [comment]
Idea for an enhancement: In the absence of the `ExcelEmitter.ForceRecalculation` option, wouldn't it make sense to force the recalculation iff BIRT generated any formula? This way, BIRT would do the right thing by default.

**Comment by speckyspooky** [comment]
The default handling of excel is that the recalculation will be done if necessary.
The forced recalculation will trigger excel to recalculate every value of an opened file and this could need lot of time.
So I see this option more as a point for the report developer as a kind of optimization level and can be used if it is really necessary.
That is the cause why I set the configuration not as active by default.

I understand the argument but I don't know which time consuming effect the changed default could cause.

**Pull request merged**
