### PR TITLE
Charts - inconsistent line thickness when imageDPI > 72 #1428

### PR DESCRIPTION
**Pull request by claesrosell**
Test of QnD fix for Line.Thickness rendering problem

### CODE REVIEW

**Comment by wimjongman** [comment]
@speckyspooky can you test this? The build artifacts are here: https://github.com/eclipse-birt/birt/actions/runs/6712091329

**Comment by speckyspooky** [comment]
I have tested the artefact. With the changes all diagram lines whil be drawn know in the same way of all digrams in the according output.

The topic is that the designer shows thick lines.
If I start PDF-emitter directly from the designer I get thick lines.

If I start the BIRT-viewer I get small lines.
If I start the PDF-emitter from viewer I get small lines.

And if I understand the ticket correctly then the thick lines is a demo but should be given on all outputs also on viewer side
and the results from there.

**Comment by wimjongman** [comment]
> I started the designer with the demo report and get thick lines.
> If I start PDF-emitter directly from the designer I get thick lines.

> If I start the BIRT-viewer I get small lines.
> If I start the PDF-emitter from viewer I get small lines.

That looks like a different issue to me.

**Comment by speckyspooky** [comment]
I'm fine with it. So we can add them to master branch.

**Comment by speckyspooky** [comment]
@claesrosell 
From my poit of view you can merge your draft into the master branch.

**Pull request merged**
