### PR TITLE
Fix DOCX font size converting issue (#1905)

### PR DESCRIPTION
**Pull request by speckyspooky**

### CODE REVIEW

**Review by merks — COMMENTED** [review]
There are many magic numbers.  Moreover the range of all size values is not covered, except I suppose to default to 10pt.   What if size is 8, -3, +5, or 100?  Is 10pt fine of all those?  Can the sizes specified in the DOM have units, like pt or px or are they purely numbers?  What's special about size.length > 2 such that you know to ignore all but the first two values?  I guess you assume then to consider only with +/- prefix and only up to the value 9.

It's not possible for fontSize to be null or have length not > 0 as tested later one.

**Comment by speckyspooky** [comment]
The W3C documentation describe the allowed values: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font](url)

grafik

Therefore values different from this range are not allowed and the default "10pt" is based on the BIRT default which is "10pt".
(On a next step I will provide user property class and then I can make the default configurable.)

Further answers to your questions:
- "size"-values couldn't have units (see documentation).
- Relative values: The prefix "+" & "-" is specific for relative values
- Relative values: only allowed for "-[0|..|3]" or "+[0|..|4]" (the +4 is a special case which is supported for the browsers but not listed at the documentation)
- Relative values: values of +2.5 will be handle through the browsers like "+2", there is no rounding up or down given

- The variable "fontSize" will be set into the second if-statement to the default "10pt" so in my point of view it cannot be null. Do you think I there is a constellation where it could be remain with the null-value?

**Review by merks — APPROVED** [review]
The explain makes it all clear now.  Thanks!  👍

**Comment by merks** [comment]
@speckyspooky 

Will this be the final change for 4.17 such that I can do another milestone build after this is merged?

**Comment by speckyspooky** [comment]
Yes, this is the last change of 4.17 from my side :o)

**Pull request merged**
