### PR TITLE
IPlatform:org.eclipse.birt.core.framework.Platform.platform is not

### PR DESCRIPTION
**Pull request by 94satya**
IPlatform:org.eclipse.birt.core.framework.Platform.platform is not initializing after OSGi Platform Launcher successful startup #1281

Updated fixed version number with version range for openpdf

### CODE REVIEW

**Comment by merks** [comment]
Which version of  com.github.librepdf.openpdf is present?  This is in the target platform:

image

So mostly your change is to exclude any version 3.x or higher, though also allowing some lower versions though lower than what was built against and tested.  These are all the versions:

https://repo1.maven.org/maven2/com/github/librepdf/openpdf/

So I don't really understand the point of this change, but I also don't see that it causes any harm...

**Comment by 94satya** [comment]
> Which version of com.github.librepdf.openpdf is present? This is in the target platform:
> 
> image
> 
> So mostly your change is to exclude any version 3.x or higher, though also allowing some lower versions though lower than what was built against and tested. These are all the versions:
> 
> https://repo1.maven.org/maven2/com/github/librepdf/openpdf/
> 
> So I don't really understand the point of this change, but I also don't see that it causes any harm...

In the Target 1.3.30 is present.
Earlier fixed version was used for the openpdf dependency, As per discussion with Thomas Gutmann (https://github.com/speckyspooky) given range is used. PFA screenshot for more details.

image

**Comment by 94satya** [comment]
> @94satya
> 
> You will need to sign an ECA as described here:
> 
> https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#setting-up-your-eclipse-and-github-account

Thanks @merks Signed ECA, If anything else needed please let me know. Thanks

**Comment by merks** [comment]
I tried revalidating but it still fails.  Is the email you used for the commit the same one associated with your Eclipse account?  Maybe it just takes a while for the database to update and I have to try again tomorrow.

**Comment by 94satya** [comment]
> I tried revalidating but it still fails. Is the email you used for the commit the same one associated with your Eclipse account? Maybe it just takes a while for the database to update and I have to try again tomorrow.

I can see different id(contains few parts of my registered mail id). I followed eclipse-launcher process and automatically this id got used. Not sure how this can be resolved. @merks  any suggestions would help?

**Comment by merks** [comment]
@94satya 

When I look at your commit, there isn't even a link to your account:

image

For other similar PR comments I can see a link to their account:

image

For the validation I see anonymous:

image

For similar PRs I see this:

image

So I don't think the author information in your commit is complete such that it is properly associated with your GitHub account.  I think you will need to amend your comment with proper author/committer details:

image

**Comment by merks** [comment]
@94satya 

This looks improved:

image

Unfortunately there now there are two commits and the one comment is the "bad" one.  You need to squash this into a single commit with the right author/committer and force push the PR...  If that's too tricky, just create a new PR with a single correct commit...

**Comment by 94satya** [comment]
> @94satya
> 
> This looks improved:
> 
> image
> 
> Unfortunately there now there are two commits and the one comment is the "bad" one. You need to squash this into a single commit with the right author/committer and force push the PR... If that's too tricky, just create a new PR with a single correct commit...

I tried amend the author, but yeah as you mentioned it has two commits includes bad one.

**Comment by speckyspooky** [comment]
I would suggest close this PR and create e new one because so you would avoid any conflicts with the old one.

**Comment by 94satya** [comment]
Thanks @speckyspooky  @merks @wimjongman closing this PR. Will raise a new PR now.

**Comment by 94satya** [comment]
New PR raised with correct author
PR: https://github.com/eclipse-birt/birt/pull/1429

**Pull request closed without merging**
