### PR TITLE
Fix of images handling of HTML embedded images which cause NullPointerException (#1436)

### PR DESCRIPTION
**Pull request by speckyspooky**
Fix of images which are embedded like URL on an html document which is embedded into a birt report element (e.g. dynamic text)

### CODE REVIEW

**Comment by speckyspooky** [comment]
@wimjongman
Hello Wim, this is a fix which should be included into BIRT4.14 to avoid the according exception.

By the way, I plan no further checkin for 4.14 only if we should get some bug notifications.
Other changes will be moved after the release of 4.14 (e.g. change of the font-mapping).

**Comment by reiner-killet** [comment]
Is fix #1440 contained in the nightly build [](https://download.eclipse.org/birt/updates/nightly/latest/index.html)?
I downloaded the RCP designer for Windows from there and the same error message still occurs.

**Comment by speckyspooky** [comment]
The fix is currently not included to the nightly built because I wait of the approval of @wimjongman 
If he has done the quality check I will consider his response and with the approval I can merge it to the master and afterwards it will go into the nightly built.

**Review by wimjongman — APPROVED** [review]
Looks good to me, Thomas.

**Pull request merged**
