### PR TITLE
Fix the image scaling based on the given dimension (#1750)

### PR DESCRIPTION
**Pull request by speckyspooky**
The scaling of the images will be done based on the given dimension if one of dimesnions are missing in relation to the given physical deimensions.

### CODE REVIEW

**Comment by speckyspooky** [comment]
I have added the test results at the issue ticket #1750

**Review by wimjongman — APPROVED** [review]
96.0 is a magic number. For the next iteration please move to a constant.

**Comment by speckyspooky** [comment]
I know the magic of the number. I didn't changed it because was original code.
I will change the number directly with this PR so we have it directly clean up.

**Comment by wimjongman** [comment]
> I know the magic of the number. I didn't changed it because was original code. I will change the number directly with this PR so we have it directly clean up.



> I know the magic of the number. I didn't changed it because was original code. I will change the number directly with this PR so we have it directly clean up.

You're the best!

**Pull request merged**
