### PR TITLE
Fix warnings and typos which was detected at #1356 and #1360

### PR DESCRIPTION
**Pull request by speckyspooky**
Fix warnings and typos which was detected at #1356 and #1360

### CODE REVIEW

**Comment by speckyspooky** [comment]
@wimjongman & @merks 
Hello guys, I created that PR to fix some java-warnings of my last changes.
The build process stopped at the start of the "Maven build"-steps because there seems to be a dependency missing.

Have you an idea how we can fix it - rerun was stopped with the same error:

Error:  Failed to resolve target definition file:/home/runner/work/birt/birt/build/org.eclipse.birt.target/org.eclipse.birt.target.target: Could not find "org.eclipse.mylyn.bugzilla_feature.feature.group/0.0.0" in the repositories of the current location -> [Help 1]

**Comment by merks** [comment]
Mylyn has been changing the IDs of most of its features.  I'll need to make updates accordingly.

**Comment by speckyspooky** [comment]
Thanks of your fast investigation

**Comment by merks** [comment]
The build with the update target platform was successful so I updated the branch of this PR...

**Pull request merged**
