### PR TITLE
 PdfEmitter, Enhancement: Enable options to set the PDF/Version & archiving formats PDF/A (A1A & A1B) #1486 

### PR DESCRIPTION
**Pull request by speckyspooky**
PdfEmitter, Enhancement: Enable options to set the PDF/Version & archiving formats PDF/A (A1A & A1B) #1486

### CODE REVIEW

**Comment by speckyspooky** [comment]
@wimjongman
This is a new enhancement of the PdfEmitter to make the PDF/A format available.
The options and the results are posted on the according enhancement-ticket.

If you need further details or you have hints on it please let me know.
I have also addressed the openPDF-issue (with version 1.3.30) of the invalid "dc:title" creation to the github-project team.
Because it must be solved there, currently we have no option to solve it directly.

**Review by wimjongman — APPROVED** [review]
Thank you for this patch, Thomas.

**Comment by hvbtup** [comment]
I'm +1 for adding PDF/A-1b, but -1 for PDF/A-1a (see my comments in the issue #1486).

**Comment by hvbtup** [comment]
None of the validators Thomas and I tested actually complains about the empty structure.
Apart from the `dc:title` issue there is another issue which some of the validators note (at least for the generated report `pdf_enhancement_version_PDF_A1A_FBfont.pdf`):

PDF: Graphics operator cm is not allowed in text object. 

But nobody's perfect and I think these are minor issues which we can address later.
So +1 for merging this from me, too.

**Comment by speckyspooky** [comment]
@merks 
Hello Ed, I started the merge of this PR some minutes ago but the built was finished with error.
It seems to be an issue with the tycho compiler plugin.

Do you know whether we should do something or do we wait till tomorrow and wait of the result of the nightly built?

2023-11-08T20:25:49.6138667Z [INFO] ------------------------------------------------------------------------
2023-11-08T20:25:49.6139247Z [INFO] BUILD FAILURE
2023-11-08T20:25:49.6139820Z [INFO] ------------------------------------------------------------------------
2023-11-08T20:25:49.6140423Z [INFO] Total time:  03:59 min
2023-11-08T20:25:49.6140927Z [INFO] Finished at: 2023-11-08T20:25:49Z
2023-11-08T20:25:49.6141606Z [INFO] ------------------------------------------------------------------------
2023-11-08T20:25:49.8479566Z [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.3:compile (default-compile) on project org.eclipse.birt.report.viewer: Compilation failure: Compilation failure: 
2023-11-08T20:25:49.8483113Z [ERROR] /home/runner/work/birt/birt/viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/soapengine/api/BoundDataColumnList.java:[111] 
2023-11-08T20:25:49.8485406Z [ERROR] 	typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.eclipse.org/birt", "BoundDataColumnList"));

**Pull request merged**
