### PR TITLE
Enhance designer viewer with spaces into path (#1466)

### PR DESCRIPTION
**Pull request by speckyspooky**
Enhance designer viewer with spaces into path (#1466)

### CODE REVIEW

**Review by merks — APPROVED** [review]
Cool. 😎 I think that will do the trick.

**Comment by speckyspooky** [comment]
@merks With your hint & support! 
But currently the build isn't runable and I cannot see the reason of the issue to my change.
Do you know is it temporary or what can I do here... - this is for me the nightmare to find unspeakable messages w/o a clear hint of the reason.

build-error

**Comment by speckyspooky** [comment]
Ok, I saw the comment before and thougth there that it is coming from the local build.
But it seems that we have it in generally.

Please let me know if I can assist you or support you with testing or research-details let me know!

**Comment by speckyspooky** [comment]
The same issue was documented last year here #1492 & #1493

**Comment by speckyspooky** [comment]
The retest of the nithgly build wasn't successful. The reason of it is that the changed code isn't currently included.
I have recompiled the "viewer.jar" and the change isn't included.

I hope that the change is added at the next nightly build.

**Comment by merks** [comment]
The build failed with a heap space error:

https://ci.eclipse.org/birt/job/build/job/master/

That seems to be an intermittent infrastructure problem.  I kicked another build:

https://ci.eclipse.org/birt/job/build/job/master/

**Comment by speckyspooky** [comment]
Oh yes, I had this issue too on Friday evening an on Saturday morning was the problem away.
Thanks for your re-start.

**Pull request merged**
