### PR TITLE
dispose of temp-files when using StreamingXlsx in XlsxEmitter #1533

### PR DESCRIPTION
**Pull request by aremund**
dispose of temporary files backing this workbook on disk after writing into output stream

### CODE REVIEW

**Review by hvbtup — APPROVED** [review]
Seems OK to me.

**Comment by speckyspooky** [comment]
Also from ym side it looks good.

**Comment by hvbtup** [comment]
@aremund  OK, please squash and merge. Thank you for contributing!

**Comment by aremund** [comment]
@hvbtup Sorry, I do not have the rights to merge into this repo :-) Would you mind doing the merge for me?

**Comment by speckyspooky** [comment]
I merged the PR to the master and the build is running now.

**Pull request merged**
