### PR TITLE
Enhance the image alignment for excel (#1760)

### PR DESCRIPTION
**Pull request by speckyspooky**
This enhancement enable the image alignment for excel output

### CODE REVIEW

**Comment by speckyspooky** [comment]
The screen documentation of the tests are added at ticket #1760

**Review by wimjongman — COMMENTED** [review]
Did you format that pagehandler source correctly?

**Comment by wimjongman** [comment]
> Did you format that pagehandler source correctly?

never mind :)

**Comment by speckyspooky** [comment]
Of course, I saw the strange compare result. Be sure, I have not changed every line and I don't know what the comparer was thinking.

**Pull request merged**
