### PR TITLE
Ensure that com.sun.el is available for report preview functionality

### PR DESCRIPTION
**Pull request by merks**
Fixed https://github.com/eclipse-birt/birt/issues/1301

### CODE REVIEW

**Comment by merks** [comment]
@speckyspooky @wimjongman 

FYI, I don't yet have the permissions to merge this myself.

**Comment by speckyspooky** [comment]
The change is checked and the PR is merged.

**Comment by merks** [comment]
@speckyspooky 

It's really great that you are testing that things actually still work!

**Comment by wimjongman** [comment]
Yes, I agree. Thanks, @speckyspooky.

**Pull request merged**
