### PR TITLE
WebViewer, enhance parameter display options with date picker (#1356)

### PR DESCRIPTION
**Pull request by speckyspooky**
The change includes the enhancement according to #1356 to add the date, time and datetime picker.

Addition on it it fix 3 additional topics:
1. Fix typo of DATETIEM_FORMAT_TYPE_* to "DATETIME_FORMAT_TYPE_*
2. Add WebPreview get the BIRT-icon as favicon
3. Optimize the HTML-declaration of FramesetFragment.jsp

### CODE REVIEW

**Comment by speckyspooky** [comment]
@merks I got an Jenkins error which means that the "program.dat" was missing.
This seams to be an build file for Jenkins.

Is it possible to restart the Jenkins process again and how can I do this?

jenkins-error

**Comment by merks** [comment]
If you login using your eclipse account you can invoke Rebuild:

image

Another way is to force push some small change, e.g, to the commit message.

The new build seems to be progressing properly...

**Comment by claesrosell** [comment]
I am currently on vacation and do not have my computer with me, hence I am not able to test this PR. From my mobile phone, it looks tidy though.
There are a lot of changed files, but this is mostly due to some clean-ups and correction of spelling errors.

One thing that draw my attention was the new patterns in FormatDateTimePattern.getPatternForCategory(). Are they used solely for parsing the data time? If it is used for presentation as well, they should probably be localized patterns instead.

Otherwise, from my perspective, this PR is okay.

**Comment by speckyspooky** [comment]
Many thanks for your fast replay and your verification during your vacation(!)

You are right the most changes are coming from the typo fix of "DATETIEM_FORMAT_TYPE_* to "DATETIME_FORMAT_TYPE_*".

And comment to "FormatDateTimePattern.getPatternForCategory()", the date time format is explicit set to non locale format because the value will be used as parsing-value for the date picker. At the beginning I used the local date time but the date will be used to prefill the default value of the date picker and not all date formats will be accepted.

The date format which will work every case is the technical format yyyy-mm-dd (which is also used on the default-value label).
Therefor I decided to use the technical format which works in every case instead to implements an additional handling.

**Pull request merged**
