### PR TITLE
Added new images and fixed typo #1329

### PR DESCRIPTION
**Pull request by speckyspooky**
Added new images and fixed typo #1329

### CODE REVIEW

**Comment by speckyspooky** [comment]
The request includes the fixes for:

- #1346  Renew web viewer parameter dialog & optional flag of textboxes
- #1343  Fix of BIRT WebViewer browser hints
- #1329 improved images of index.jsp

**Comment by speckyspooky** [comment]
@merks 
If you have questions to my changes let me know.

**Comment by merks** [comment]
The target is generated so whatever you change manually will be overwritten the next time the setup resolves the target platform. It’s also minimized to remove implicit transitive requirements.  Let’s not go back to manually maintaining it until we hit a brick wall again. 

What is the rationale for the target changes?

**Comment by speckyspooky** [comment]
I'm fine with the automated re-writting of the target.

The change was done through eclipse automatically and additional with it there appears some errors this afternoon on Jenkins so I thought the new target will fix the issue. And the PR was buildable.

But with your note I understand that the both topics have no dependency and I confirm the auto-generation is better.

**Comment by speckyspooky** [comment]
@merks 
Could you please let me knwo during the day if I can go ahead with the merge. Thanks!

**Comment by merks** [comment]
Notice the "Update branch" drop-down says cannot rebase due to conflicts.  I think that's because you modified the *.target which I already fixed in a separate PR.  So my sense is that something will be overwritten by this...

I suppose I can regenerate it and update it again if necessary...

**Comment by speckyspooky** [comment]
Thanks for your check, so I will later merge it and test the built at all.

**Pull request merged**
