### PR TITLE
Calender picker for Date report parameter

### PR DESCRIPTION
**Pull request by krishnakittu**

### CODE REVIEW

**Comment by claesrosell** [comment]
I have not had time to test this yet, but hopefully, I have time in the coming days.

**Review by hvbtup — APPROVED** [review]

**Comment by hvbtup** [comment]
@claesrosell Should we merge this now and close #926?

**Comment by claesrosell** [comment]
No, this is not yet ready for merging.

**Comment by krishnakittu** [comment]
@claesrosell Anything to be done for merging?..

**Comment by claesrosell** [comment]
This was added by #1356

**Pull request closed without merging**
