### PR TITLE
Initial prototype for porting to Jetty 12

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-birt/birt/issues/1447

### CODE REVIEW

**Comment by merks** [comment]
This is just to see how well the build works, and for sharing with @claesrosell

**Comment by merks** [comment]
Apparently the build doesn’t test that the web app works.

**Comment by claesrosell** [comment]
I configured my remote ref wrong so now we have a new branch called pr-1448 in the main repo. I will remove it shortly.
Does github provide any means to push to a PR or does I need to create a PR to your branch in your fork?

**Comment by merks** [comment]
I’m sure there is a way. But I don’t know the way. Don’t worry about starting a new branch or new different PR. Do whatever is easiest.

**Comment by wimjongman** [comment]
> I configured my remote ref wrong so now we have a new branch called pr-1448 in the main repo. I will remove it shortly. Does github provide any means to push to a PR or does I need to create a PR to your branch in your fork?

@claesrosell You can create a pull request and then force push to your branch at any moment to have the PR updated

**Comment by wimjongman** [comment]
@merks can this be closed?

**Pull request closed without merging**
