### PR TITLE
Excel, Spudsoft, Improvement of the list element handling (#1432)

### PR DESCRIPTION
**Pull request by speckyspooky**
Excel, Spudsoft - Improvement the list element handling #1432 
- AbstractRealTableCellHandler, fixed class cast issues
- FlattenedListHandler, added missing (override) methods
- AbstractHandler, comment out error handling because the list container- & content-elements haven't a specific implementation

### CODE REVIEW

**Comment by speckyspooky** [comment]
Test report and results added to the original discussion #1427

**Comment by speckyspooky** [comment]
@hvbargen 
Hello Henning, my plan would be to merge that PR for the upcoming release of BIRT 4.14.
It would be nice if you had time to review the change. Thanks in advance.

**Review by hvbtup — APPROVED** [review]
Looks OK to me.
It is difficult to predict if these changes might cause issues with edge cases in other reports, but we'll never be able to have 100% test coverage anyway, so I'm fine with merging.

**Comment by speckyspooky** [comment]
@merks 
Hello Ed,
today I pushed 2 PR to the master branch but the built-process won't be finished.
The problem is that a source/feature couldn't be found:

Could not find "org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group/0.0.0".
Have you an idea of the problem for that?

Thanks in advance Thomas

repository_error

**Pull request merged**
