### PR TITLE
do not autosize columns in case of StreamingXlsx eclipse-birt#1703

### PR DESCRIPTION
**Pull request by aremund**

### CODE REVIEW

**Review by speckyspooky — CHANGES_REQUESTED** [review]
Instead to use the check of "XSSFSheet" twice with your condition, it would be better to set it directly as an own "if-block" before the "if (calcWidth > 1.0) {..." starts.

So you can avoid your special inner "} else if (" which will not set in all cases in compare to the old version.

**Comment by aremund** [comment]
I understand what you mean and to start with, I implemented it this way.
But what I still want in the StreamingXlsx-case is setting the column to the calculated width. I would need to repeat this calculation for the StreamingXlsx-case. (the line `state.currentSheet.setColumnWidth(col, (int) calcWidth);`)
(Or am I now the confused one and do see the obvious anymore?)

**Comment by aremund** [comment]
It's official, I am the one not seeing the obvious anymore. I adapted the code accordingly.

**Review by speckyspooky — APPROVED** [review]

**Comment by aremund** [comment]
Sorry, I cannot merge due to my permissions. Would be happy, if someone else can merge.

**Comment by merks** [comment]
For the future, please keep a PR to a single commit by amending and force pushing 

https://github.com/eclipse-birt/birt/pull/1701#issuecomment-2123940466

**Pull request merged**
