### PR TITLE
Fix prepared statement setNull() #1365

### PR DESCRIPTION
**Pull request by speckyspooky**
Fix prepared statement setNull() #1365

### CODE REVIEW

**Comment by speckyspooky** [comment]
@merks 
Hi there today I have a problem with the build process on jenkins side.
You fixed the a mylin issue with #1367 to correct the build process on Jenkin side I get a familiar issue.
I'm wondering because your last bult was running and also my production merge.

The jenkins error message are:

jenkins-error2

jenkins-error

Could you please assist here again. Thanks in advance.

**Comment by merks** [comment]
The error suggests you are using an older version of the target platform in the build, i.e., comparing before and after the fix I did:

image

I'm going to rebase your branch:

image

That should start a new build with the latest version of the target platform.

**Comment by merks** [comment]
Note that any other PRs you started before the target platform was fixed will need to be rebased if you need to build them again...

**Comment by speckyspooky** [comment]
Sorry, I'm didn't understand the issue because I checked in the "Statement.class" and before I pushed all changes fro birt-master-branche into my folk.
Yes, I see in your screen that my version is an older and not corresponding to your fix. But I'm confused because realy I thought with the merge from master to my folk to my branch I have the latest version.

**Comment by speckyspooky** [comment]
But you are right I created the new local branch before your fix was bushed and after your push I refreshed.
If I understand you then it isn't enough to start only a change refresh from the master-branch in this case.

**Comment by merks** [comment]
I'm not such a great Git expert.    I personally try to ensure  I have master checked out and pulled.   Then I create my branch, commit, and push to my fork as the remote.  I avoid working on more than one PR at a time.  I'm not sure how to manually rebase after master has diverged.   My poor man's approach is to rename the branch.  Check out master and pull.  Create a new branch with the same name as I used before.  Cherry pick the change from the renamed branch on the newly-created branch, and force push to my fork.  I'm sure there's a better way. 😱

**Pull request merged**
