### PR TITLE
Improved handling of space characters at file-url and svg-images base64-encoded (#1416)

### PR DESCRIPTION
**Pull request by speckyspooky**
The changes fix the 3 topics of the issue-ticket #1416

### CODE REVIEW

**Comment by speckyspooky** [comment]
@merks 
Hello Ed, yesterday evening I had trouble with my fork an the disc space (no free space available).
I fixed that issue on my fork with a change of the ci.yml. There I added a "clean up" section.

Today I created this PR and I got a familiar issue with the PR of the master-branche - see my screen below.
Therefore I added also the "clean up" section of ci.yml on this PR.
Afterwards the PR was finished successfully.

But from my side you are the "expert" of the full built-process.
Therefore please let me know if I should remove the change of ci.yml or I should change something e.g. title of the section.

### ci.yml - section
```
    - name: Clean up log files
      run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
```

### Original built error
built-no-space-left-on-device

**Comment by merks** [comment]
Unfortunately I know next to nothing about GitHub actions and about the *.yml stuff.  That's something @wimjongman setup up and if there are problems there, he will know better how to deal with that.  In the end, the continuous-integration build is what actual produces update sites, so it really only matters that that build works...

**Comment by wimjongman** [comment]
Thomas, please move the Github actions change to a separate PR.

**Comment by speckyspooky** [comment]
I will split the both changes and create an own PR for the Github actions.

**Comment by speckyspooky** [comment]
Hello Wim, I have movd the Github action change to PR #1426 so both topics are splitted.
You can go ahead with the validation of both PRs.

**Pull request merged**
