### PR TITLE
Enhancement to improve the svg-image-handling and the usage of data-url #1386

### PR DESCRIPTION
**Pull request by speckyspooky**
enhancement to improve the svg-image-handling and the usage of data-url #1386

### CODE REVIEW

**Comment by speckyspooky** [comment]
For documentation reasons of the test results I will add some screens according to the issue ticket
and also the used BIRT-report with the 2 used images (png & svg). All other used images included on the report like data-URL or added via https-link (URL).

### Screen of the designer with the change
enh-designer-preview-compare-data-url-and-svg


### Screen of the output formats HTML, PDF and DOCX with the change
enh-image-compare-data-url-and-svg


### Test report & images
Hint: before the report can be used the local path to the images must be changed.
[enhanced_handling_image_overview.zip](https://github.com/eclipse-birt/birt/files/12296296/enhanced_handling_image_overview.zip)


### Output: PDF & DOCX with the change
[enhanced_handling_image_overview.zip](https://github.com/eclipse-birt/birt/files/12296303/enhanced_handling_image_overview.zip)

**Comment by hvbtup** [comment]
Looking at the output, it looks very well.
I'm very busy ATM and will be on holiday in weeks 33 and 34, so I don't have the time to look at the code.
I recommend to let someone else review the code.

**Comment by speckyspooky** [comment]
@hvbtup

Thanks for your first look.
One additional information, I double checked the PDF-file to verify the SVG-graphics (to have real SVG images in there).
The result is that the SVGs are added like original SVGs and not transformed to raster images. The raster images are only uses on the office types (PPTX, DOCX, XSLX).

Here is my some of 600% with the Adobe Reader to see the raster details in compare to the SVG:


svg-raster

**Review by wimjongman — COMMENTED** [review]
This code looks good to me. Can you add tests?

**Comment by speckyspooky** [comment]
Thanks for your check.

Yes, I can do it and set it on my list.
(The next step will be to remove some standard warnings of the changed classes on an own PR.)

**Comment by ilnur-z** [comment]
i have NPE on method org.eclipse.birt.report.engine.util.SvgFile.isSvg(String) then uri is null.
I think that because some brackets needed:

`
if (uri != null && **(**uri.endsWith(".svg") || uri.toLowerCase().contains(URL_IMAGE_TYPE_SVG)**)**) 
`

(just like on method org.eclipse.birt.report.engine.util.SvgFile.isSvg(String, String, String))

**Pull request merged**
