### PR TITLE
For birt-runtime-osgi copy javax.xml.soap jar to the lib folder

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-birt/birt/issues/1340

### CODE REVIEW

**Comment by merks** [comment]
@speckyspooky 

This adds the jar to the example lib folder and in the war's lib folder it's there as well.  

I'm going out now, so please feel free to squash and merge this when the builds complete, I assume successfully.

**Comment by speckyspooky** [comment]
@merks 
I will do it when the built is finished.

**Comment by speckyspooky** [comment]
The change was an partial success. We have a new issue based on the changes.
You comment the plugin-copy of some libraries:

- org.apache.commons.logging_*.jar
- org.apache.axis_*/lib/*.jar
- org.apache.commons.discovery_*/lib/*.jar
- javax.xml.rpc_*/lib/*.jar

Now we get Error 500 on the example reports (see below). Please remove the comment and leave the copy part to the plugin-folder like before.

issue-after-soap

**Comment by speckyspooky** [comment]
With the latest changes we miss 2 files which are required to execute the report-generation:

- commons-discovery-0.2.jar
- org.apache.commons.logging_1.2.0.v20180409-1502.jar

I compared the latest version "lib"-folder with the version before.
If I add the both files manuelly at the "lib"-folder then the report can be generated correctly.

**Comment by speckyspooky** [comment]
PR #1348

**Pull request merged**
