### PR TITLE
Required dependencies of osgi-runtime (report generation) #1340

### PR DESCRIPTION
**Pull request by speckyspooky**
Added missing dependencies of osgi-runtime

### CODE REVIEW

**Comment by merks** [comment]
I have the following working locally and comparing the two lib folders:

image

The soap mystery is more clear now because formerly that came from the saaj.jar.  Also javax.xm.bind is missing and should be replaced by jakarta.xml.bind, which export javax packages, unless it was never relevant, but best not to make assumptions.

I really don't want to pull things from the designer product.  Better that we pull everything from the target folder of the project itself.

I have a pull request coming and I thing it's better we abandon this one...

**Comment by merks** [comment]
I think this fix is better and most probably more complete:

https://github.com/eclipse-birt/birt/pull/1349

This fix pulls everything from the target folder of the project itself rather than pulling things from other products in other projects.

**Comment by speckyspooky** [comment]
Ok, I'm with you.

My PR will finished in some minutes and I will not push them to the master.
I will wait your improved version so that I can do my retest with the latest version tomorrow.

**Comment by speckyspooky** [comment]
I close the PR because the #1349 "Copy more content into the lib folder of birt-runtime-osgi"
implements the optimized and better version for the dependencies.

**Pull request closed without merging**
